---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-gui
  labels:
    app: vote-gui
  namespace: pickypoll
spec:
  template:
    metadata:
      labels:
        app: vote-gui
    spec:
      containers:
        - name: app
          stdin: true
          image: stephenmerc/vote-gui:6
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
  selector:
    matchLabels:
      app: vote-gui