---
apiVersion: v1
kind: Service
metadata:
  name: vote-gui
  namespace: pickypoll
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: vote-gui
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gui-ingress
  namespace: pickypoll
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  rules:
    - host: pickypoll.com
      http:
        paths:
          -  path: /
             pathType: Prefix
             backend:
              serviceName: vote-gui
              servicePort: 80
  tls:
    - hosts:
      - pickypoll.com
      - www.pickypoll.com
      secretName: pickypoll-tls
